Repository Necktschnagge/tobor-games, pull requests merged in 2024-02, with the labels that each got.

#73 Feature status bar
  src/gui_interactive_controller.cpp
  src/gui_interactive_controller.h
  src/mainwindow.cpp
  src/mainwindow.h
Labels: Qt, GUI

#105 README: rename project to tobor
  CMakeLists.txt
  README.md
Labels: documentation

#119 Pieces Coloring Permutation + Keyboard Input with QKeyEvents
  src/color_generator.cpp
  src/color_generator.h
  src/custom_traits.h
  src/debug_utils.cpp
  src/debug_utils.h
  src/gui_interactive_controller.cpp
  src/gui_interactive_controller.h
  src/key_event_filter.cpp
  src/key_event_filter.h
  src/main.cpp
  src/mainwindow.cpp
  src/mainwindow.h
  src/mainwindow.ui
Labels: Qt, GUI, generator-engine

#135 Remove obsolete menau bar action handlers
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement

#134 Fixes to enable different piece quantities
  src/gui_interactive_controller.cpp
  src/gui_interactive_controller.h
  src/solver.h
  src/tobor_svg.h
Labels: engine
